import 'package:flutter/material.dart';
import '../models/agent_model.dart';
import '../services/supabase_service.dart';
import '../services/auth_service.dart';

class AgentProvider extends ChangeNotifier {
  final SupabaseService _supabaseService = SupabaseService();
  final AuthService _authService = AuthService();
  
  List<Agent> _agents = [];
  bool _isLoading = false;
  String? _errorMessage;
  Agent? _selectedAgent;

  List<Agent> get agents => _agents;
  bool get isLoading => _isLoading;
  String? get errorMessage => _errorMessage;
  Agent? get selectedAgent => _selectedAgent;

  // Load all agents for current user
  Future<void> loadAgents() async {
    final userId = _authService.getCurrentUser()?.id;
    if (userId == null) {
      _errorMessage = 'User not authenticated';
      notifyListeners();
      return;
    }

    _isLoading = true;
    _errorMessage = null;
    notifyListeners();

    try {
      _agents = await _supabaseService.getAgents(userId);
    } catch (e) {
      _errorMessage = 'Failed to load agents: $e';
      debugPrint('Error loading agents: $e');
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  // Create new agent
  Future<bool> createAgent({
    required String name,
    required String description,
    required String systemPrompt,
    String? voiceId,
    String? avatarUrl,
  }) async {
    final userId = _authService.getCurrentUser()?.id;
    if (userId == null) {
      _errorMessage = 'User not authenticated';
      notifyListeners();
      return false;
    }

    _isLoading = true;
    _errorMessage = null;
    notifyListeners();

    try {
      final agent = Agent(
        id: '', // Will be generated by Supabase
        name: name,
        description: description,
        systemPrompt: systemPrompt,
        voiceId: voiceId,
        avatarUrl: avatarUrl,
        createdAt: DateTime.now(),
        userId: userId,
      );

      await _supabaseService.createAgent(agent);
      await loadAgents(); // Refresh the list
      return true;
    } catch (e) {
      _errorMessage = 'Failed to create agent: $e';
      debugPrint('Error creating agent: $e');
      return false;
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  // Update existing agent
  Future<bool> updateAgent({
    required String agentId,
    String? name,
    String? description,
    String? systemPrompt,
    String? voiceId,
    String? avatarUrl,
  }) async {
    _isLoading = true;
    _errorMessage = null;
    notifyListeners();

    try {
      final Map<String, dynamic> updates = {};
      if (name != null) updates['name'] = name;
      if (description != null) updates['description'] = description;
      if (systemPrompt != null) updates['system_prompt'] = systemPrompt;
      if (voiceId != null) updates['voice_id'] = voiceId;
      if (avatarUrl != null) updates['avatar_url'] = avatarUrl;

      await _supabaseService.updateAgent(agentId, updates);
      await loadAgents(); // Refresh the list
      return true;
    } catch (e) {
      _errorMessage = 'Failed to update agent: $e';
      debugPrint('Error updating agent: $e');
      return false;
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  // Delete agent
  Future<bool> deleteAgent(String agentId) async {
    _isLoading = true;
    _errorMessage = null;
    notifyListeners();

    try {
      await _supabaseService.deleteAgent(agentId);
      await loadAgents(); // Refresh the list
      return true;
    } catch (e) {
      _errorMessage = 'Failed to delete agent: $e';
      debugPrint('Error deleting agent: $e');
      return false;
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  // Select agent for editing/viewing
  void selectAgent(Agent agent) {
    _selectedAgent = agent;
    notifyListeners();
  }

  // Clear selected agent
  void clearSelectedAgent() {
    _selectedAgent = null;
    notifyListeners();
  }

  // Get agent by ID
  Agent? getAgentById(String id) {
    try {
      return _agents.firstWhere((agent) => agent.id == id);
    } catch (e) {
      return null;
    }
  }
}